<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HVDIVD27GA41104" ignored="0" name="Loans" tests="5" failures="1" timestamp="24 Jun 2019 19:06:57 GMT" time="0.047" errors="0">
  <testcase name="demo" time="0.007" classname="test.testNG1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.testNG1.demo(testNG1.java:13)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- demo -->
  <testcase name="demo1" time="0.001" classname="test.testNG1"/>
  <testcase name="homeapiLogin" time="0.001" classname="test.homeloan"/>
  <testcase name="homemobileLogin" time="0.004" classname="test.homeloan"/>
  <testcase name="homewebLogin" time="0.001" classname="test.homeloan"/>
</testsuite> <!-- Loans -->
